import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";
import AivoWrapper from "@/components/Aivo/AivoWrapper";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL('https://aivur.com.br'),
  title: "AIVUR — Inteligência que evolui resultados",
  description: "Sistema inteligente de evolução do conhecimento com questões, trilhas personalizadas e IA aplicada ao aprendizado.",
  openGraph: {
    title: "AIVUR — Inteligência que evolui resultados",
    description: "Sistema inteligente de evolução do conhecimento com questões, trilhas personalizadas e IA aplicada ao aprendizado.",
    url: "https://aivur.com.br", // Substitua pelo domínio real quando em prod
    siteName: "AIVUR",
    images: [
      {
        url: "/og-image-wa-v2.png", // Next.js assumirá a URL base se for relativo na raiz public/
        width: 1200,
        height: 630,
        alt: "AIVUR Preview",
      }
    ],
    locale: "pt_BR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AIVUR — Inteligência que evolui resultados",
    description: "Sistema inteligente de evolução do conhecimento com questões, trilhas personalizadas e IA aplicada ao aprendizado.",
    images: ["/og-image-wa-v2.png"],
  },
  icons: {
    icon: [
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' }
    ],
    apple: '/apple-touch-icon.png',
  },
  manifest: '/manifest.json', // Will be generated by manifest.ts
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem={false}>
          {children}
          <AivoWrapper />
        </ThemeProvider>
      </body>
    </html>
  );
}
